### ISSUE TITLE
Wrong summary on GET "/issue/:id" (?)

### ISSUE THREAD

**Issue by ricardojmendez** [yogthos/memory-hole#12]
The summary for the API used to return an issue [states that it returns the 10 most recent issues](https://github.com/yogthos/memory-hole/blob/master/src/clj/memory_hole/routes/services.clj#L144-L148).   Looking at schema this seems to be a mistake, since it either returns an issue or an error, not a collection.

**Comment by yogthos** [comment]
Good catch, and I cleaned up some other API docs as well in the process.
