### ISSUE TITLE
Error: running lein run migrate

### ISSUE THREAD

**Issue by ThinhPTran** [yogthos/memory-hole#23]
Dear yogthos, 

I am new to Clojurescript and trying to learn from your project but when I run command "lein run migrate" I get a error information as in attached file. 
[errlog.txt](https://github.com/yogthos/memory-hole/files/621154/errlog.txt)
Please help me out. 

Best regards, 
Thinh P. Tran

**Comment by yogthos** [comment]
The error says that the database connection settings are not correct. Check that you have Postgres setup, and that the connection string in `:database-url` is valid.

**Comment by ThinhPTran** [comment]
Dear yogthos, 

Many thanks for your suggestion. The server is running now. After running lein run migrate, lein run, and lein figwheel, I try to surf to the url: 0.0.0.0:3449 but I get this error on the browser page: 

Figwheel Server: Resource not found

Keep on figwheeling. 

It seems that it is looking for html file. Should I create a new one or there is some error and it is not expected. 

Best regards, 
Thinh P. Tran

**Comment by yogthos** [comment]
Hi,

Glad to hear the app runs. The `0.0.0.0:3449` is a port for hot loading code in development. The app should be serving the page at `localhost:3000` by default.

**Comment by ThinhPTran** [comment]
Dear yogthos, 

Many thanks for your help. It is working now. I am enjoying reading the code. Wish you a happy day. 

Best regards, 
Thinh P. Tran
