### ISSUE TITLE
Wrong order of recently viewed issues

### ISSUE THREAD

**Issue by jhamrsky** [yogthos/memory-hole#38]
Hello, 

I think that recently viewed issues should be ordered by `ASC` instead of `DESC` - I would expect last viewed / created issue to be on top of the page, not on bottom. It was ok until f840fe07dcd82c090ee15599dd8df1b6b01ee703.

Furthermore, are we sure that `last_viewed_date` column name corresponds to its use? I can see this value to be updated when issue is created and updated, therefore it seems that:
* `last_viewed_date` should be `last_modified_date`
* `recently-viewed-issues` should be `recently-modified-issues`
* should be set when issue is created (initialization) and modified (update)

**Comment by yogthos** [comment]
Good catch, I think the views metric is probably more useful than update metric. So, I'm thinking it would be better to keep the column, but update it when issue is selected as opposed to updated.

**Comment by yogthos** [comment]
I just pushed an update with the  fix, let me know if it looks good.
